const loans = [
  {
    loanId: 44068301,
    firstName: 'kehinde',
    lastName: 'edward',
    user: 'kennyedward99@gmail.com',
    tenor: 8,
    amount: 50000,
    status: 'approved',
    repaid: false,
    balance: 52500,
    interest: 2500,
    paymentInstallment: 6562.5,
    purpose: 'Business',
    createdOn: new Date(),
  },
  {
    loanId: 82928475,
    firstName: 'taiwo',
    lastName: 'charles',
    user: 'taewole@gmail.com',
    tenor: 3,
    amount: 90000,
    status: 'approved',
    repaid: false,
    balance: 94500,
    interest: 4500,
    paymentInstallment: 31500.00,
    purpose: 'Education',
    createdOn: new Date(),
  },
  {
    loanId: 73637837,
    firstName: 'taiwo',
    lastName: 'charles',
    user: 'taewole@gmail.com',
    tenor: 3,
    amount: 90000,
    status: 'approved',
    repaid: false,
    balance: 94500,
    interest: 4500,
    paymentInstallment: 31500.00,
    purpose: 'Education',
    createdOn: new Date(),
  },
  {
    loanId: 34526719,
    firstName: 'taiwo',
    lastName: 'charles',
    user: 'taewole@gmail.com',
    tenor: 3,
    amount: 90000,
    status: 'approved',
    repaid: true,
    balance: 94500,
    interest: 4500,
    paymentInstallment: 31500.00,
    purpose: 'Travel',
    createdOn: new Date(),
  },
];

export default loans;
